services:
  redis:
    image: redis:latest
    container_name: container_redis
    ports:
      - "6379:6379"
    networks:
      - sys_net
    volumes:
      - /redis:/redis
    restart: unless-stopped
  
  backend:
    build:
      context: ./backend
    ports:
      - "7861:7861"
    networks:
      - sys_net
    container_name: container_backend
    environment:
      - BACKEND_IP=0.0.0.0
      - VLLM_PORT=1370
      - REDIS_PORT=6379
      - BACKEND_PORT=7861
    volumes:
      - ./backend:/usr/src/app
      - ./utils:/usr/src/app/utils   
      - /var/run/docker.sock:/var/run/docker.sock
      - ../logs:/usr/src/app/logs
      - /models:/models
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped
  

networks:
  sys_net:
    name: sys_net
    driver: bridge